@startuml
class StandAloneWrapper << (S,#0FF077) Script >> {
  + runBot()
  + parseConfig(configfile) : access_info
  + algorithm(stb)
}
package Management <<Folder>> {

}
package Bot <<Folder>> {
  class SocialBot {
    --
    + __init__(self, access_info)
    + activate_log(self, path, name)
    + __log(self, message)
    + tweet(self, text) : resp
    + retweet(self, tweet_id) : resp
    + favor(self, status=None, status_id=None) : resp
    + send_dm(self, username=None, user_id=None, message=None) : resp
    + search_tweet(self, term) : resp
    + search_user(self, term) : resp
    + get_subscriptions(self, username=None, user_id=None, count=20, page=-1) : resp
    + get_tweets(self, username=None, user_id=None) : resp
    + get_followers(self, username=None, user_id=None, page=-1) : resp
    + get_my_replies(self) : resp
    + get_my_retweets(self) : resp
    + get_my_mentions(self) : resp
    + stream(self, users=None, terms=None) : resp
    + limit_stream(self, users=None, terms=None, limit=None) : resp
  }
}

StandAloneWrapper -- SocialBot
@enduml
