@startuml
package PresentationLayer <<Folder>> {

}
package BusinessLayer <<Folder>> {

}
package DataAccessLayer <<Folder>> {
  class InternalAPI {
    --
    + __init__(self, access_info)
  }
}
@enduml
